### ISSUE TITLE
Module parse failed: Unexpected token

### ISSUE THREAD

**Issue by axeldelafosse** [storybookjs/addon-react-native-web#12]
Hey! Thanks a lot for working on this!

I was working on a custom Webpack config and then found this-- this is great!

I'm making it even harder by running this inside a monorepo. And I think my local package isn't transpiled correctly.

Here is my config:

```
const path = require('path')

module.exports = {
  stories: [
    '../src/**/*.stories.mdx',
    '../src/**/*.stories.@(js|jsx|ts|tsx)',
    '../../../packages/app/**/*.stories.@(js|jsx|ts|tsx)'
  ],
  addons: [
    '@storybook/addon-links',
    '@storybook/addon-essentials',
    {
      name: '@storybook/addon-react-native-web',
      options: {
        modulesToTranspile: [
          'react-native-reanimated',
          '@gorhom/bottom-sheet',
          '@gorhom/portal',
          'dripsy',
          '@dripsy/core',
          '@dripsy/gradient',
          'twrnc',
          'moti',
          '@motify/components',
          '@motify/core',
          '@motify/skeleton',
          '@motify/interactions',
          'expo-next-react-navigation',
          '@zeego/menu',
          '@zeego/dropdown-menu'
        ],
        babelPlugins: ['react-native-reanimated/plugin'],
      }
    }
  ],
  core: {
    builder: 'webpack5'
  },
  typescript: { reactDocgen: false },
  webpackFinal: async (config) => {
    config.module.rules[config.module.rules.length - 1].include.push(
      path.resolve('../../packages/app')
    )

    return config
  }
}

```

We can see that we are transpiling these modules:
```
 {
    test: /\.(js|jsx|ts|tsx)$/,
    loader: 'babel-loader',
    include: [
      '/Users/axel/Documents/showtime/showtime/node_modules/@gorhom/bottom-sheet/',
      '/Users/axel/Documents/showtime/showtime/node_modules/@gorhom/portal/',
      '/Users/axel/Documents/showtime/showtime/node_modules/dripsy/',
      '/Users/axel/Documents/showtime/showtime/node_modules/@dripsy/core/',
      '/Users/axel/Documents/showtime/showtime/node_modules/@dripsy/gradient/',
      '/Users/axel/Documents/showtime/showtime/node_modules/twrnc/',
      '/Users/axel/Documents/showtime/showtime/node_modules/moti/',
      '/Users/axel/Documents/showtime/showtime/node_modules/@motify/components/',
      '/Users/axel/Documents/showtime/showtime/node_modules/@motify/core/',
      '/Users/axel/Documents/showtime/showtime/node_modules/@motify/skeleton/',
      '/Users/axel/Documents/showtime/showtime/node_modules/@motify/interactions/',
      '/Users/axel/Documents/showtime/showtime/node_modules/expo-next-react-navigation/',
      '/Users/axel/Documents/showtime/showtime/node_modules/@zeego/menu/',
      '/Users/axel/Documents/showtime/showtime/node_modules/@zeego/dropdown-menu/',
      '/Users/axel/Documents/showtime/showtime/packages/app'
    ],
    options: { presets: [Array], plugins: [Array] }
  }
  ```
  
  But then I get this error:
  ```
  99% done plugins webpack-hot-middlewarewebpack built preview 3511084d6ae29d5b529d in 14552ms
ModuleParseError: Module parse failed: Unexpected token (448:8)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|       });
|       return (
>         <Component {...props} ref={this._setComponentRef} {...platformProps} />
|       );
|     }
    at handleParseError (/Users/axel/Documents/showtime/showtime/node_modules/@storybook/builder-webpack5/node_modules/webpack/lib/NormalModule.js:969:19)
```
    
Any idea why?

**Comment by axeldelafosse** [comment]
Also I'm getting this when transpiling `react-native-reanimated`:

```
99% done plugins webpack-hot-middlewarewebpack built preview ddc1f41a8fe372662a94 in 19870ms
ModuleBuildError: Module build failed (from ../../node_modules/babel-loader/lib/index.js):
SyntaxError: /Users/axel/Documents/showtime/showtime/node_modules/react-native-reanimated/lib/createAnimatedComponent.js: Missing class properties transform.
  67 |
  68 |   class AnimatedComponent extends React.Component {
> 69 |     _invokeAnimatedPropsCallbackOnMount = false;
     |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  70 |
  71 |     constructor(props) {
  72 |       super(props);
    at File.buildCodeFrameError (/Users/axel/Documents/showtime/showtime/node_modules/@babel/core/lib/transformation/file/file.js:249:12)
```

But I do have `@babel/plugin-proposal-class-properties` (from Storybook babel config) 🤷‍♂️

```
    [
      '/Users/axel/Documents/showtime/showtime/node_modules/@storybook/core-common/node_modules/@babel/plugin-proposal-class-properties/lib/index.js',
      [Object]
    ],
```

I remember having a similar issue with Next.js babel config at some point. But that's not the case anymore.

I double checked the Webpack and the Babel config, everything looks good to me... Appreciate your help, thank you in advance!

**Comment by axeldelafosse** [comment]
OK I'm pretty sure it's due to a conflict with Babel configs (I have a custom `babelrc.json`) so I moved this to another app, `apps/storybook` instead of `apps/next` directly. `react-native-reanimated` is now transpiled.

Last error:
```
99% done plugins webpack-hot-middlewarewebpack built preview 41c06d39e08a1ee390ad in 12723ms
ModuleParseError: Module parse failed: Unexpected token (13:30)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| import processColor from '../../exports/processColor';
|
> const normalizeColor = (color?: number | string, opacity?: number = 1): void | string => {
|   if (color == null) return;
|
    at handleParseError (/Users/axel/Documents/showtime/showtime/apps/storybook/node_modules/@storybook/builder-webpack5/node_modules/webpack/lib/NormalModule.js:969:19)
```

Looks like `react-native-web` isn't? I'm not sure to understand what's happening...

By the way I can create a story using `import { Button } from 'react-native'` but it's not working when using `import { Button } from 'app/design-system'`

**Comment by dannyhw** [comment]
@axeldelafosse hey thanks for raising this issue. A few things

- react native web won't need to be transpiled its usually something else that's using it
- when you get the class properties missing error it just means that the loader didn't get applied for that package, it's one of the ones applied by defaultnin this add-on


Are you able to provide a reproduction of this in a public repo? I would really like to debug this a bit.

**Comment by axeldelafosse** [comment]
> react native web won't need to be transpiled its usually something else that's using it

Yeah I know! This is why I don't get it. What's using it that don't get transpiled? I think this is a deeper issue with React Native for Web. There is a bunch of issues related to tree shaking because React Native for Web gets imported by a lot of different packages and it ends up included multiple times... Would be cool to solve this but to be honest, again, I don't get it.

Working on a repro right now. Thank you!

**Comment by axeldelafosse** [comment]
Here is a working example: https://github.com/axeldelafosse/storybook-rnw-monorepo. Now I'll try to reproduce the issue.

**Comment by dannyhw** [comment]
@axeldelafosse once you have the issue reproduced let me know and I'll have a look after I finish work 👍

**Comment by axeldelafosse** [comment]
@dannyhw thank you :) Just added a bug!

`moti` uses `react-native-reanimated` but it doesn't get transpiled. Should we transpile nested dependencies?

Don't know if this helps but `next-transpile-modules` is working very well on Next.js: https://github.com/martpie/next-transpile-modules

**Comment by axeldelafosse** [comment]
@dannyhw thank you :) just added a bug in the monorepo!

`moti` uses `react-native-reanimated` but it doesn't get transpiled. It makes me think... shouldn't we transpile nested dependencies?

I don't know if this helps but `next-transpile-modules` is working very well: https://github.com/martpie/next-transpile-modules

**Comment by dannyhw** [comment]
I'm not sure why that would happen, I was under the impression that nested packages were already included. I'll definitely look into that though.

Regarding the next-transpile-modules package I've also seen expo has some webpack stuff and I've been looking into it a bit. Theres potential to re-use some functionality from either for sure.

**Comment by axeldelafosse** [comment]
Well actually `react-native-reanimated` isn't a direct dep so maybe it's just an issue with Babel?

**Comment by axeldelafosse** [comment]
Oh we posted at the same time. Yeah I don't think that's an issue with nested packages after all 🤷‍♂️

**Comment by dannyhw** [comment]
> Oh we posted at the same time. Yeah I don't think that's an issue with nested packages after all 🤷‍♂️

in your config int he initial issue you have this line commented, if you uncomment this does it work?
`// 'react-native-reanimated',`

**Comment by axeldelafosse** [comment]
Nope doesn't work. Sorry for posting the snippet with comments. Editing right now.

**Comment by dannyhw** [comment]
> Nope doesn't work. Sorry for posting the snippet with comments. Editing right now.

Hmm ok I think I can help more once I have a chance to debug it in the repro. 

You might have already done so but I would recommend looking through more of the error log to see if maybe another package is causing this. Sometimes the first few errors are more of a false flag.

**Comment by axeldelafosse** [comment]
Yeah the issue is now the same in my app than it the [repro](https://github.com/axeldelafosse/storybook-rnw-monorepo).

**Comment by dannyhw** [comment]
> Yeah the issue is now the same in my app than it the [repro](https://github.com/axeldelafosse/storybook-rnw-monorepo).

@axeldelafosse ok thanks for providing that repro 🙇 , I'll take a look as soon as can,

**Comment by dannyhw** [comment]
@axeldelafosse so I managed to get it working by trying out some random stuff. I'll make a pr on your repro to show what I changed.

Basically it seems like the module resolution for babel from the app folder is not working in the expected way.

I just add this in your webpack config and it starts working. I think by going through the expo webpack config it should be possible to figure out what makes this work.

```
 const { withUnimodules } = require('@expo/webpack-config/addons')
    return withUnimodules(config, {
      babel: {
        dangerouslyAddModulePathsToTranspile: ['app']
      }
    })
```

**Comment by dannyhw** [comment]
@axeldelafosse I opened a pr on your repro https://github.com/axeldelafosse/storybook-rnw-monorepo/pull/1/files

It's working but needs a bit of investigation to find a proper solution.

**Comment by axeldelafosse** [comment]
Ahhh! Nice catch! Thanks a lot man!

It makes sense since we use Next.js for Storybook. `withUnimodules` is used by the Next.js adapter to make everything work together, so of course we need to use it here too.

But yeah still unsure what exactly makes it work correctly. I'm guessing it's because it

> Transpile and remove expo modules from Next.js externals.

cf. https://github.com/expo/expo-cli/blob/d3333ce6cbb01c5290b63a106722ab7607b6ebf4/packages/webpack-config/src/addons/withUnimodules.ts#L154

But maybe I'm wrong. I don't know how Storybook works under the hood and how it leverage Next.js to work.

Feels like there is three things at play here: using Next.js for Storybook, using React Native for Web (with Next.js and Expo modules), and using a separate package inside a monorepo to host the UI components and stories.

**Comment by axeldelafosse** [comment]
I also discovered another issue: we now need to `import React from 'react'` on every file used by Storybook, both stories and components. I pushed a repro in the repo with a component working and another one with the bug.

That doesn't seem to happen when using bare Next.js and Storybook setup like here for example: https://storybook.js.org/blog/get-started-with-storybook-and-next-js/

**Comment by dannyhw** [comment]
@axeldelafosse is this an eslint error or does it break the components when running the app?

Otherwise the react docs suggest this on the babel config so I might need to adjust it.
```
{
  "presets": [
    ["@babel/preset-react", {
      "runtime": "automatic"
    }]
  ]
}
```

**Comment by dannyhw** [comment]
@axeldelafosse if I make a PR with this babel change can you test it on your repro?

**Comment by axeldelafosse** [comment]
It breaks but only inside Storybook. Yeah of course happy to test it!

**Comment by dannyhw** [comment]
@axeldelafosse see #13 you can try the canary version of the package: 0.0.8-canary.13.a1fda33.0

**Comment by axeldelafosse** [comment]
Hmm. It's not working. I'm pretty sure that setting the runtime to `automatic` is the correct solution tho...

**Comment by dannyhw** [comment]
> Hmm. It's not working. I'm pretty sure that setting the runtime to `automatic` is the correct solution tho...

Strange 🤔 , I will have a look on your repo again when I have time. Maybe some other babel config is getting in the way.

**Comment by dannyhw** [comment]
@axeldelafosse sorry I didn't get a chance to look at this yet, were you able to make any progress? I'll have another look later today if I can.

**Comment by dannyhw** [comment]
I ended up going down a massive rabbit hole trying to replicate some of the expo webpack config and managed to get something working for the repro, however it wouldn't work in the example project when I tried the changes over here. I'll try again soon.

**Comment by dannyhw** [comment]
Resolved by #13

**Comment by dannyhw** [comment]
Version 0.0.8 out now! :). You can update to the stable version now if you want @axeldelafosse 
https://github.com/storybookjs/addon-react-native-web/releases/tag/v0.0.8

**Comment by dannyhw** [comment]
@IlyaTaidi could you create a branch/PR with those changes so I can see what you have so far?

**Comment by jhonnymoreira** [comment]
I was facing the same problem as described in this issue and I was able to solve with the following code (Dripsy was erroring):

```js
// .storybook/main.js
{
  // ...
  addons: [
    {
      name: '@storybook/addon-react-native-web',
      options: {
        modulesToTranspile: ['dripsy', '@dripsy'],
        projectRoot: '../',
      },
    },
  ],
  // ...
}
```

The `projectRoot` combined with `modulesToTranspile` was key to make it all work properly.

**Comment by rimbener** [comment]
> I was facing the same problem as described in this issue and I was able to solve with the following code (Dripsy was erroring):
> 
> ```js
> // .storybook/main.js
> {
>   // ...
>   addons: [
>     {
>       name: '@storybook/addon-react-native-web',
>       options: {
>         modulesToTranspile: ['dripsy', '@dripsy'],
>         projectRoot: '../',
>       },
>     },
>   ],
>   // ...
> }
> ```
> 
> The `projectRoot` combined with `modulesToTranspile` was key to make it all work properly.

Thank you so much!!! I fought with webpack config for about 3 hours, and all I really needed was  `@storybook/addon-react-native-web`
