### ISSUE TITLE
Some modules are not rendered on storybook, but rn-webapp can render it

### ISSUE THREAD

**Issue by lacsinagramar** [storybookjs/addon-react-native-web#14]
### Describe the bug
Some modules are not rendered on storybook, but rn-webapp can render it.

### Steps to reproduce the behavior

1. Create a story, using a component that uses an unsupported module. I will use `@react-native-community/blur` as an example for this issue.

### Expected behavior

For the storybook to render the component, since rn-webapp can render it.

### Screenshots and/or logs

![image](https://user-images.githubusercontent.com/29629828/142842374-fa9c6d7c-c881-439b-90e2-401222bf02f1.png)

### Environment

 - OS: Windows
 - Node.js version: 12.22.0
 - NPM version: 6.14.11
 - Browser (if applicable): Chrome
 - Browser version (if applicable): 96.0.4664.45

### Additional context

here's my storybook `main.js`

```javascript
module.exports = {
	core: {
		builder: 'webpack5',
	},
	stories: [
		'../src/**/*.stories.mdx',
		'../src/**/*.stories.@(js|jsx|ts|tsx)',
	],
	addons: [
		'@storybook/addon-links',
		'@storybook/addon-essentials',
		'@storybook/addon-react-native-web',
	],
}
```

Here's my story file `BlurView.stories.tsx`:

```javascript
import React from 'react'
import {BlurView} from '@atoms/BlurView/BlurView'
import {ComponentStory} from '@storybook/react'
import {Text, View} from 'react-native'

export default {
	title: 'atoms/BlurView',
	component: BlurView,
}

const Template: ComponentStory<typeof BlurView> = (args) => (
	<>
		<View
			style={{
				backgroundImage: 'url(MY_URL_HERE)',
				backgroundSize: 'cover',
				backgroundPosition: 'center',
				height: 400,
			}}>
			<BlurView {...args}>
				<Text style={{color: 'white'}}>
					This is a text inside BlurView
				</Text>
			</BlurView>
		</View>
	</>
)

export const Basic = Template.bind({})
Basic.args = {
	blurAmount: 10,
}
```

and my BlurView component:
```javascript
import React from 'react'
import {
	BlurView as Blur,
	BlurViewProperties,
} from '@react-native-community/blur'

export interface IBlurView extends BlurViewProperties {
	children?: JSX.Element | JSX.Element[]
}

export const BlurView = ({
	children,
	blurType = 'dark',
	blurAmount,
	...props
}: IBlurView) => (
	<Blur
		{...props}
		blurType={blurType}
		blurAmount={blurAmount}
		reducedTransparencyFallbackColor="white">
		{children}
	</Blur>
)
```

**Comment by dannyhw** [comment]
@lacsinagramar I don't think this is an issue with rendering the blur view, seems more like it's not resolving the blur view component in '@atoms/BlurView/BlurView'. 

Are you using a mono repo?

**Comment by lacsinagramar** [comment]
> @lacsinagramar I don't think this is an issue with rendering the blur view, seems more like it's not resolving the blur view component in '@atoms/BlurView/BlurView'.
> 
> Are you using a mono repo?

Yes `@atoms/BlurView/BlurView` is the component at the last of the message. `@atoms` is just an alias config

**Comment by dannyhw** [comment]
> > @lacsinagramar I don't think this is an issue with rendering the blur view, seems more like it's not resolving the blur view component in '@atoms/BlurView/BlurView'.
> > Are you using a mono repo?
> 
> Yes `@atoms/BlurView/BlurView` is the component at the last of the message. `@atoms` is just an alias config

Have you added this alias config to the storybook webpack config?

**Comment by lacsinagramar** [comment]
> > > @lacsinagramar I don't think this is an issue with rendering the blur view, seems more like it's not resolving the blur view component in '@atoms/BlurView/BlurView'.
> > > Are you using a mono repo?
> > 
> > Yes `@atoms/BlurView/BlurView` is the component at the last of the message. `@atoms` is just an alias config
> 
> Have you added this alias config to the storybook webpack config?

I think it's already configured in the `babel.config.js` cause other components under my `@atoms` folder are working.

**Comment by dannyhw** [comment]
@lacsinagramar could you share a repository with a reproduction of this problem? That would really help to debug it.

**Comment by lacsinagramar** [comment]
@dannyhw Sure, I'll try to reproduce a repo for this.

**Comment by dannyhw** [comment]
you could try the new canary version `0.0.8-canary.13.d8d70a6.0`, this new version is meant to deal with some mono repo issues.

**Comment by dannyhw** [comment]
@lacsinagramar you could try the new canary version 0.0.8-canary.13.d8a51bb.0 from my current PR, this new version is meant to deal with some mono repo issues.

**Comment by lacsinagramar** [comment]
@dannyhw Sorry I didn't have the time to reproduce a repo. I specifically fixed the `BlurView` error. I had to copy my webpack config on my `next.config.js` to `.storybook/webpack.config.js`

Though, there are still some modules that fails like `react-native-flash-message`. I'm seeing module transpiling on our `next.config.js` using `next-transpile-modules`, so I will try to do transpiling config on my storybook. Will update if it fixes it.

**Comment by lacsinagramar** [comment]
Update: I added the modules to `modulesToTranspile` then I get this error on storybook.

![image](https://user-images.githubusercontent.com/29629828/143259371-6dc42d60-fe6c-4a1e-a473-b22e6550118b.png)

@dannyhw am I missing something?

**Comment by dannyhw** [comment]
> Update: I added the modules to `modulesToTranspile` then I get this error on storybook.
> 
> ![image](https://user-images.githubusercontent.com/29629828/143259371-6dc42d60-fe6c-4a1e-a473-b22e6550118b.png)
> 
> @dannyhw am I missing something?

@lacsinagramar  did you update to the latest version?

**Comment by lacsinagramar** [comment]
Updating to latest version (`0.0.10`) gave an error.

![image](https://user-images.githubusercontent.com/29629828/143296560-1fb5305f-4099-4e08-9108-c3430dfe728f.png)

But I fixed it by changing line 58-62 into:
```javascript
const root = options && options.projectRoot && process.cwd();
const modules = [
  ...DEFAULT_INCLUDES,
  ...(options && options.modulesToTranspile || []),
];
```

And all of my modules work now! Thank you! 💖

Should I create a PR for the code that I changed?

**Comment by lacsinagramar** [comment]
Updating to latest version (`0.0.10`) gave an error.

![image](https://user-images.githubusercontent.com/29629828/143296560-1fb5305f-4099-4e08-9108-c3430dfe728f.png)

But I fixed it by changing line 58-62 into:
```javascript
const root = options && options.projectRoot && process.cwd();
const modules = [
  ...DEFAULT_INCLUDES,
  ...(options && options.modulesToTranspile || []),
];
```

And all of my modules work now! Thank you! 💖

@dannyhw  Should I create a PR for the code that I changed?

**Comment by dannyhw** [comment]
@lacsinagramar glad it working :). 

Actually the idea is that you could pass a project root or we assume its the cwd (current working directory).
So that would be like this:
`const root = options && options.projectRoot || process.cwd();`

And yes would be great if you can open a PR 🙏

**Comment by lacsinagramar** [comment]
> @lacsinagramar glad it working :).
> 
> Actually the idea is that you could pass a project root or we assume its the cwd (current working directory). So that would be like this: `const root = options && options.projectRoot || process.cwd();`
> 
> And yes would be great if you can open a PR 🙏

PR (#18) for this is up now. Thanks 🚀
