### ISSUE TITLE
[Bug] react-native-gesture-handler not working after 0.0.13

### ISSUE THREAD

**Issue by Wuyialex** [storybookjs/addon-react-native-web#26]
### Describe the bug

react-native-gesture-handler does not work after version 0.0.13.

**Comment by dannyhw** [comment]
Could you check any errors in both the web console and on the storybook output? There should ideally be something to help explain this issue. In my tests it was working.

**Comment by dannyhw** [comment]
@Wuyialex could you also include more information about your project.

Like the version of storybook being used and your config

**Comment by Wuyialex** [comment]
> @Wuyialex could you also include more information about your project.
> 
> Like the version of storybook being used and your config
> 
> And if you can provide a public reproduction repo that would be really great.

The test environment is as follows:
@storybook/addon-react-native-web 0.0.13/0.0.14
react-native-gesture-handler 1.10.3
react-native-reanimated 2.3.0-beta4

**Comment by dannyhw** [comment]
@Wuyialex what about any errors in the console or in the build output?

**Comment by Wuyialex** [comment]
> @Wuyialex what about any errors in the console or in the build output?

No errors occur in build ouput/console. However, the gesture doesn't actually work.

**Comment by dannyhw** [comment]
@Wuyialex what about errors in the browser dev console?

**Comment by dannyhw** [comment]
@Wuyialex if there are no errors at all I can't do much without a reproduction that I can debug on. 

If you can't provide a reproduction repo are you able to provide steps to replicate the problem you have?

**Comment by Wuyialex** [comment]
> @Wuyialex if there are no errors at all I can't do much without a reproduction that I can debug on.
> 
> If you can't provide a reproduction repo are you able to provide steps to replicate the problem you have?

We are currently looking for a way to communicate this phenomenon more clearly. Since we are using app + web monorepo, it is not easy to provide it separately. But I'll find a way. Thank you for your interest.

**Comment by Wuyialex** [comment]
> @Wuyialex if there are no errors at all I can't do much without a reproduction that I can debug on.
> 
> If you can't provide a reproduction repo are you able to provide steps to replicate the problem you have?

@dannyhw, I made public reproduction repo.

(needs `yarn && yarn storybook`) 

DragBox works with gesture (0.0.12)
https://github.com/Wuyialex/rn-next-storybook-web-monorepo

DragBox does not work with gesture (0.0.13)
https://github.com/Wuyialex/rn-next-storybook-web-monorepo/tree/fix/%40storybook%2Faddon-react-native-web%400.0.13

**Comment by dannyhw** [comment]
@Wuyialex thanks for making a reproduction that will really help a lot. I'll do my best to figure it out and let you know soon.

**Comment by dannyhw** [comment]
@Wuyialex if you change the project root you can solve your problem `projectRoot: path.resolve(__dirname, '../../'),`

Not sure why exactly its broken in 0.0.13 however this happens because you are importing from outside of the current project folder. By default your code is only transpiled if its part of the projectRoot which defaults to the current working directory.

```
  addons: [
    '@storybook/addon-links',
    '@storybook/addon-essentials',
    {
      name: '@storybook/addon-react-native-web',
      options: {
        modulesToTranspile: ['dripsy', '@dripsy/core', 'react-native-reanimated'],
        babelPlugins: ['react-native-reanimated/plugin'],
        projectRoot: path.resolve(__dirname, '../../'),
      },
    },
  ],
```

**Comment by Wuyialex** [comment]
> projectRoot: path.resolve(__dirname, '../../'),

Wow, Adding projectRoot solved problem. It would be better if docs updated:) Thanks!
