### ISSUE TITLE
Some of the packages just need a dummy placeholder or platform name removed

### ISSUE THREAD

**Issue by matijagrcic** [storybookjs/addon-react-native-web#34]
Hi,

Not sure if you want to treat this as an issue or not but just wanted to tell you that some of the packages need either a placeholder
**index.js** https://github.com/flexible-agency/react-native-email-link/pull/100/commits/4d08d5eae1c27531c5e1dbc011ebc69ef1b87887

https://github.com/flexible-agency/react-native-email-link/pull/100

or in some cases a file called [PassKit.android.js](https://github.com/miyabi/react-native-passkit-wallet/blob/master/PassKit.android.js) or [PassKit.ios.js](https://github.com/miyabi/react-native-passkit-wallet/blob/master/PassKit.ios.js) needs to be renamed to not include the platform name and then it all works fine.

This is easily fixable with **patch-package** but just wondering if a setting to look for **android/ios** or **index.js** would be of value similar to the **projectRoot**.

Thanks for your huge effort to bring latest and greatest SB and docs to RN.

**Comment by dannyhw** [comment]
@matijagrcic thanks for the kind words :)

This I think this is something that would be solved by library maintainers.

Or if the android/ios file would work on the web you could add the android/ios extensions to the webpack accepted extensions and it would pick those as a last resort.

something like this in main.js:

```
webpackFinal: (config: any) => {
  config.resolve.extensions = [
    ...config.resolve.extensions,
    'android.js',
    'ios.js',
  ];
  return config
}
```

**Comment by dannyhw** [comment]
I don't think theres anything to do here so I'm closing the issue, let me know if you want to reopen :)
