### ISSUE TITLE
[Bug] No register file in repo

### ISSUE THREAD

**Issue by stereodenis** [storybookjs/addon-react-native-web#41]
### Describe the bug

Can't run Storybook after adding this addon

### Steps to reproduce the behavior

1. `addons: ['@storybook/addon-react-native-web']`
2. run `yarn sb-rn-get-stories`
3. it generates `import "@storybook/addon-react-native-web/register";`

### Expected behavior

App and Storybook runs

### Screenshots and/or logs

![image](https://user-images.githubusercontent.com/1406461/192431631-8828a819-8c37-4e9e-9bab-38de3083778a.png)

### Environment

 - OS: iOS
 - Node.js version: v17.5.0
 - NPM version: 8.18.0
 - "@storybook/addon-react-native-web": "0.0.18",
 - "@storybook/react": "6.5.12",
 - "@storybook/react-native": "6.0.1-beta.7",
 - "babel-plugin-react-native-web": "^0.17.7",
 - "babel-loader": "8.2.5",
 - "react-dom": "17.0.2",
 - "react-native-web": "^0.17.7",

**Comment by dannyhw** [comment]
This addon is not intended for `@storybook/react-native` you use it with the react storybook to be able to render react native components in the web.
