### ISSUE TITLE
Issue with showing SVGs components

### ISSUE THREAD

**Issue by gmferraz** [storybookjs/addon-react-native-web#50]
Hi Danny, excellent work with the library.
I've been wondering if there's any way to configure this addon to work properly with [react-native-svg-transformer](https://github.com/kristerkari/react-native-svg-transformer). I followed their docs on how to setup react-native to be able to import `.svg` files and use them directly as a component. Most of my components have SVG components inside them and they all show this following error when opened on storybook. 
 
<img width="787" alt="Captura de Tela 2023-01-23 às 17 16 38" src="https://user-images.githubusercontent.com/108529265/214140938-011b220a-77f6-4fc4-83b7-d7e1938a2243.png">

I tried messing around a bit on the `.storybook/metro.config.js` and adding the module to `modulesToTranspile`  file but I couldn't get anywhere.

Any help will be very appreciated. Thanks!

**Comment by dannyhw** [comment]
@gmferraz you will probably need to add a webpack loader for svgs since metro isn't used when rendering on the web. Though I would have expected svgs to load fine on the web. Can you share a reproduction repo?

**Comment by gmferraz** [comment]
@dannyhw got it, will create a reproduction repo asap and contact you back

**Comment by gmferraz** [comment]
@dannyhw here it is [reproduction repo](https://github.com/gmferraz/rn-web-sb-SVG-issue)

**Comment by gmferraz** [comment]
Tried to follow the steps described in https://github.com/storybookjs/storybook/issues/18557 but no success

**Comment by dannyhw** [comment]
@gmferraz will take a look soon, thanks for providing the reproduction

**Comment by gmferraz** [comment]
Hi @dannyhw, have you got a chance to take a look at this issue? Thanks!

**Comment by dannyhw** [comment]
Sorry! Been busy and I didn't get around to it. I'll take a look today. Thanks for reminding me.

**Comment by huynhtastic** [comment]
@dannyhw any update here? Not sure what I could do but happy to help if needed!

**Comment by dannyhw** [comment]
in the repo for svg transformer they are using @svgr/webpack in the web example

**Comment by dannyhw** [comment]
```
  webpackFinal: (config) => {
    const fileLoaderRule = config.module.rules.find((rule) =>
      rule.test.test('.svg'),
    );
    fileLoaderRule.exclude = /\.svg$/;
    config.module.rules.push({
      test: /\.svg$/,
      use: ['@svgr/webpack', 'url-loader'],
    });
    return config;
  },
```

I believe that something like this should work

**Comment by gmferraz** [comment]
Great @dannyhw! Thank you. The SVGs are not breaking the story anymore but they are all showing as squares. Do you have any idea what may be causing this?  

<img width="46" alt="Captura de Tela 2023-03-13 às 08 11 57" src="https://user-images.githubusercontent.com/108529265/224685559-102b3e5c-777e-4d04-ae5e-6f2fb085e41d.png">

**Comment by gmferraz** [comment]
Thank you so much @dannyhw! Worked perfectly, I can prepare a PR adding this to FAQ or the docs since it seems to bee a frequent issue if you want to 😄! Thanks again.

**Comment by dannyhw** [comment]
That sounds like a great idea, and yes always love getting prs 😄🙏

**Comment by YOEL311** [comment]
for me its work only with
``"@svgr/webpack":"6.5.1"``

version

**Comment by dannyhw** [comment]
a section was added to the docs with information on how to get svgs working

**Comment by DeynekaYuriy** [comment]
> webpackFinal: (config) => {
>     const fileLoaderRule = config.module.rules.find((rule) =>
>       rule.test.test('.svg'),
>     );
>     fileLoaderRule.exclude = /\.svg$/;
>     config.module.rules.push({
>       test: /\.svg$/,
>       exclude: /node_modules/,
>       use: [
>         {
>           loader: '@svgr/webpack',
>         },
>       ],
>     });
>     return config;
>   },

LOVE YOU MAN!

**Comment by LucasLFurini** [comment]
I'm having a TS error "Cannot find module" when importing .svg files inside stories files, anybody has this issue as well?

**Comment by dannyhw** [comment]
@LucasLFurini try this https://stackoverflow.com/a/45887328

**Comment by km00776** [comment]
> [@huynhtastic](https://github.com/huynhtastic) [@gmferraz](https://github.com/gmferraz)
> 
> Again I'm sorry I keep pushing this back, I kept meaning to do it but stuff keeps coming up.
> 
> Anyway I debugged it today and got it working.
> 
> install `@svgr/webpack`
> 
> then If you put this in your main.js then svgs should be imported correctly
> 
> ```
>   webpackFinal: (config) => {
>     const fileLoaderRule = config.module.rules.find((rule) =>
>       rule.test.test('.svg'),
>     );
>     fileLoaderRule.exclude = /\.svg$/;
>     config.module.rules.push({
>       test: /\.svg$/,
>       exclude: /node_modules/,
>       use: [
>         {
>           loader: '@svgr/webpack',
>         },
>       ],
>     });
>     return config;
>   },
> ```

Whats the alternative for vite? tried svgr but doesn't work...

**Comment by dannyhw** [comment]
@km00776 maybe https://www.npmjs.com/package/vite-plugin-svgr

**Comment by km00776** [comment]
@dannyhw  Hey thanks for the quick response, I've added svgr() but it still errors with this 

![Image](https://github.com/user-attachments/assets/2af7b821-4222-45e0-85b1-343a6cd3be82)

I'm wondering if i might need to pass additional svgroptions... It works fine on the simulators, just not working on storybook

**Comment by dannyhw** [comment]
maybe try adjusting the includes option for svgr?

```
  // A minimatch pattern, or array of patterns, which specifies the files in the build the plugin should include.
  include: "**/*.svg",
```

**Comment by km00776** [comment]
> maybe try adjusting the includes option for svgr?
> 
> ```
>   // A minimatch pattern, or array of patterns, which specifies the files in the build the plugin should include.
>   include: "**/*.svg",
> ```
> 
> seems like it has a default like `include = "**/*.svg?react",` for some reason

Ah yes, that works, thanks a lot! :)
