### ISSUE TITLE
[Question] How do you configure to use @storybook/addon-a11y

### ISSUE THREAD

**Issue by Awethentique** [storybookjs/addon-react-native-web#59]
Hi Danny, excellent work with this addition to storybook.

### Describe the bug

@storybook/addon-a11y does not seem to work with React Native on the device which is ok.
However, using the web browser `yarn storybook` I was hoping to see the "Accessibility" tab.

### Steps to reproduce the behavior

1. I have installed the addon `yarn add @storybook/addon-a11y --dev`
2. Configured the `main.js` file with 
```
export default {
  addons: [
    ...other-addons,
    '@storybook/addon-a11y'
  ],
};
```
3. Run `yarn storybook` 
4. Do not see "Accessiblility" tab on web view

### Expected behavior

Hoping to see  "Accessiblility" tab on web view like the "Design" tab from the 'storybook-addon-designs' addon

### Screenshots and/or logs
![image](https://user-images.githubusercontent.com/1106670/230794511-0452895d-8cb1-4e3d-9fea-5d6795201d21.png)

### Additional context

Any help finding a way to get this working will be very appreciated. Thanks!

**Comment by dannyhw** [comment]
This should work, do you see any errors in the console/terminal?

**Comment by Awethentique** [comment]
I dont get any errors. Everything builds and compiles fine

I cloned this repo https://github.com/dannyhw/react-native-storybook-starter

I then added the addon via `yarn add @storybook/addon-a11y --dev`

Configured the `main.js` file with
```
export default {
  addons: [
    ...other-addons,
    '@storybook/addon-a11y'
  ],
};
```

I have also tried adding the following addons:
```
    '@storybook/addon-interactions',
    '@storybook/addon-coverage',
```
They don't seem to work either.

With `addon-interactions` I get the following error when I add in a `play` function:
![image](https://user-images.githubusercontent.com/1106670/230921356-3aaae89e-1bec-4fa8-b544-2968940afc74.png)

![image](https://user-images.githubusercontent.com/1106670/230922339-1e29e26b-1fb0-4b9b-8e8e-ba89ae1c72fb.png)

<img width="498" alt="image" src="https://user-images.githubusercontent.com/1106670/230922426-cbfc3b70-58ec-4122-b04a-f45e88b205ef.png">



When I tried adding `@storybook/addon-docs` and `'../src/**/*.mdx',` to `stories`
I seem to be getting the following error

![image](https://user-images.githubusercontent.com/1106670/230924169-90579980-655c-442a-a35c-d00ed4edc5ba.png)

**Comment by dannyhw** [comment]
what version of those packages did you install? make sure you aren't using v7 alongside v6 since there are breaking changes.

**Comment by Awethentique** [comment]
Thank you, that did the trick.
I checked my package.json and some modus were using "^7.0.2"
