### ISSUE TITLE
[Bug] react-native-reanimated does not work on Storybook 6/7

### ISSUE THREAD

**Issue by kchuah** [storybookjs/addon-react-native-web#62]
### Describe the bug

This is a follow-up from https://github.com/storybookjs/addon-react-native-web/issues/61. 
`react-native-reanimated` doesn't work with latest `@storybook/addon-react-native-web` and throws the following error. 

```
caught TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at _updatePropsJS (index.js:1:1)
    at UpdateProps.js:1:1
    at Set.forEach (<anonymous>)
    at _f (UpdateProps.js:1:1)
    at _f (useAnimatedStyle.js:2:1)
    at Mapper._f [as mapper] (useAnimatedStyle.js:2:1)
    at Mapper.execute (Mapper.js:1:1)
    at MapperRegistry.execute (MapperRegistry.js:1:1)
    at JSReanimated._onRender (JSReanimated.js:1:1)
_
```
In the originating issue, OP mentioned being able to resolve with Storybook version 7.0.9, I have attempted to do the same with the minimal reproduction example per the link below but am still facing the same issue. I am also facing the same problems with Storybook 6.5.13 and 7.0.13

https://github.com/ppong/addon-react-native-web-debug

### Steps to reproduce the behavior

I created a minimal example by running
```
npx sb init --type react
yarn add react-dom react-native-web babel-plugin-react-native-web @storybook/addon-react-native-web --dev
```

and also updated the config

```
module.exports = {
  addons: [
    /*existing addons,*/
    {
      name: '@storybook/addon-react-native-web',
      options: {
        modulesToTranspile: ['react-native-reanimated'],
        babelPlugins: ['react-native-reanimated/plugin'],
      },
    },
  ],
};
```
Here is a repo with the minimal example: https://github.com/ppong/addon-react-native-web-debug

### Expected behavior

reanimated animation should work

### Screenshots and/or logs

![Screenshot 2023-05-23 at 12 27 22 pm](https://github.com/storybookjs/addon-react-native-web/assets/5734042/18ccd1b2-495a-4a6b-baa5-3653696a561b)

### Environment

OS: MacOS
Node.js version: v18.2.0
NPM version: 8.9.0
Browser (if applicable): chrome

**Comment by kchuah** [comment]
I was able to resolve this issue by downgrading `react-native-web` to 0.18.10 and noted that these issues might be related:

https://github.com/react-navigation/react-navigation/issues/11356
https://github.com/software-mansion/react-native-reanimated/pull/4352

**Comment by dannyhw** [comment]
@kchuah thanks for the update, sorry for the delay in responding. Seems like its an issue on those packages then?

**Comment by kchuah** [comment]
@dannyhw yes I would believe so

**Comment by dannyhw** [comment]
I've just tried this and everything was working as expected. I can reopen if you think there are still issues.
