### ISSUE TITLE
[Bug] use with package that using reactNativeRanimated failed

### ISSUE THREAD

**Issue by YOEL311** [storybookjs/addon-react-native-web#73]
### Describe the Bug

I followed the documentation [here](https://github.com/storybookjs/addon-react-native-web#configuring-popular-libraries) on integrating the `react-native-reanimated` library with Storybook.

When I create components containing animations, everything works as expected. However, when I incorporate another package that also includes animations, the web version of the app breaks (while the native app remains unaffected).

I am using Storybook version 7, and you can find the relevant commit [here](https://github.com/YOEL311/storybookPublic/commit/8afc03b0149df228cc7602c935899c525ce448df).

You can view an example of my package [here](https://github.com/YOEL311/componentsPublic).

### Steps to Reproduce

1. **Clone the repository:**
   ```bash
   git clone git@github.com:YOEL311/storybookPublic.git
   cd storybookPublic
   yarn
   yarn storybook

in web i got this error

````
[Reanimated] `useAnimatedStyle` was used without a dependency array or Babel plugin. Please explicitly pass a dependency array, or enable the Babel/SWC plugin.
````


However, removing the animation from the external library and keeping only the animation of my app resolves the issue. You can see the specific code [here](https://github.com/YOEL311/storybookPublic/blob/8afc03b0149df228cc7602c935899c525ce448df/components/Buttons/ButtonLess.tsx#L59).

I have added the configuration for react-native-reanimated [here](https://github.com/YOEL311/storybookPublic/blob/8afc03b0149df228cc7602c935899c525ce448df/.storybook/main.js#L18).

**Comment by dannyhw** [comment]
@YOEL311 you have three configurations for the same config you must have only one

in your config: 
```
    '@storybook/addon-react-native-web',
    {
      name: '@storybook/addon-react-native-web',
      options: {
        modulesToAlias: {
          'react-native-linear-gradient': 'react-native-web-linear-gradient',
        },
      },
    },
    {
      name: '@storybook/addon-react-native-web',
      options: {
        modulesToTranspile: ['react-native-reanimated'],
        babelPlugins: [
          '@babel/plugin-proposal-export-namespace-from',
          'react-native-reanimated/plugin',
        ],
      },
    },
  ],
```

expected config:
```
    {
      name: '@storybook/addon-react-native-web',
      options: {
       modulesToAlias: {
          'react-native-linear-gradient': 'react-native-web-linear-gradient',
        },
        modulesToTranspile: ['react-native-reanimated'],
        babelPlugins: [
          '@babel/plugin-proposal-export-namespace-from',
          'react-native-reanimated/plugin',
        ],
      },
    },
```

**Comment by YOEL311** [comment]
Hi @dannyhw 
Thank you for your reply. I appreciate it.
I made the necessary changes, but I still encountered the same error.

**Comment by dannyhw** [comment]
@YOEL311  you still have it two times

**Comment by dannyhw** [comment]
look here remove this line 6
https://github.com/YOEL311/storybookPublic/blob/8c936a99299efb6fc8d9eb52f59e2c12c4ab459b/.storybook/main.js#L6

**Comment by YOEL311** [comment]
ok but I still got the error

![image](https://github.com/storybookjs/addon-react-native-web/assets/39925212/05157d48-3068-4b80-b3d7-9f6195e9498e)

**Comment by dannyhw** [comment]
Well you can also just manually add the dependency array to your useAnimatedStyle

for example:

```
  const animatedStyles = useAnimatedStyle(() => ({
    transform: [{ translateX: withSpring(translateX.value * 2) }],
  }), translateX.value);

```

**Comment by dannyhw** [comment]
@YOEL311 I found the issue, you need to add your package to the modulesToTranspile or add the dependency array in the component in that package

update the modulesToTranspile to this:

```
     modulesToTranspile: [
          'react-native-reanimated',
          'test-package-yoel-test',
        ],
```

**Comment by YOEL311** [comment]
@dannyhw 
Thanks
I have to give you my salary (:
